### ISSUE TITLE
Post-processing (Clustering) Slow

### ISSUE THREAD

**Issue by rayhou0710** [davyneven/SpatialEmbeddings#7]
Thank you for publishing the code!

I ran the test using your pretrained model on the car class but found out that the avg post-processing time is about 391 ms per image on a Titan Xp GPU which is much slower than the number reported in the paper. May I ask if I missed anything? Thanks!

**Comment by davyneven** [comment]
Hi rayhou, it is indeed correct that the clustering is slower than mentioned in the paper. This is because this repo includes a python version of the clustering, and not the c++ variant which we used for timing. Given our license agreement, we only release the 'research' version and not the optimized production version. However, given the python version, I think it is quite easy to convert to c++, you should then definitely see an improvement.

**Comment by rayhou0710** [comment]
Thank you for the reply!
